jupyter:
  build: ./
  ports:
    - "8888:8888"
  command: start-notebook.sh --NotebookApp.token='${JUPYTER_PASS} --NotebookApp.iopub_data_rate_limit=50000000'
  volumes:
    - ${LOCAL_DATA_PATH}:/home/jovyan/work
  environment:
    DB_HOST: "${DB_HOST}"
    DB_USER: "${DB_USER}"
    DB_PASS: "${DB_PASS}"
    DB_NAME: "${DB_NAME}"
    PG_DB_HOST: "${PG_DB_HOST}"
    PG_DB_USER: "${PG_DB_USER}"
    PG_DB_PASS: "${PG_DB_PASS}"
    PG_DB_NAME: "${PG_DB_NAME}"
